# ------------------------------------------------------------------
# Paramètres généraux du projet
# ------------------------------------------------------------------

paths:
  # CSV d’entrée (déjà enrichi avec la colonne « index »)
  input_csv: "datas/inputs/fichier_traites.csv"
  # CSV de sortie après l’ajout de la colonne « index » et l’enrichissement PDF
  input_csv_enrichi: "datas/outputs/fichier_traites_enrichis.csv"
  # Répertoire contenant les PDF à associer
  pdf_dir: "datas/pdf"
  # Emplacements des résultats intermédiaires / finaux pour vlm_llm
  extraction_output_vlm_llm: "datas/outputs/vlm_llm/predictions.csv"
  ocr_vlm: "datas/outputs/vlm_llm/ocr.csv"
  extraction_final_output_vlm_llm: "datas/outputs/vlm_llm/final_predictions.csv"
  # Emplacements des résultats intermédiaires / finaux pour tesseract_llm
  extraction_output_tess_llm: "datas/outputs/tesseract_llm/predictions.csv"
  ocr_tess: "datas/outputs/tesseract_llm/ocr.csv"
  extraction_final_output_tess_llm: "datas/outputs/tesseract_llm/final_predictions.csv"
  # Emplacements des résultats intermédiaires / finaux pour vlm_vlm
  extraction_output_vlm_vlm: "datas/outputs/vlm_vlm/predictions.csv"
  extraction_final_output_vlm_vlm: "datas/outputs/vlm_vlm/final_predictions.csv"
  # Emplacements de la base TOPAD code_postal_commune_topad
  code_postal_commune_topad : "datas/inputs/TOPAD/code_postal_commune_topad.csv"
  # Emplacements de la base TOPAD code_pays_2024
  code_pays_2024 : "datas/inputs/TOPAD/code_pays_2024.csv"
  # Emplacements de la base TOPAD code_postal_drom_com
  code_postal_drom_com : "datas/inputs/TOPAD/code_postal_drom_com.csv"


  


# ------------------------------------------------------------------
# Configuration du logger
# ------------------------------------------------------------------
logging:
  # Niveau de logs : DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  # Modèle de nom de fichier de log (déjà utilisé dans le script)
  filename_pattern: "%Y-%m-%d_%H-%M-%S.log"
  # Format des messages de log
  format: "%(asctime)s [%(levelname)s] %(name)s – %(message)s"
  # Format de la date affichée dans les logs
  datefmt: "%Y-%m-%d %H:%M:%S"

# ------------------------------------------------------------------
# Options Pandas (lecture / écriture)
# ------------------------------------------------------------------
pandas:
  read_options:
    dtype: str          # toutes les colonnes sont lues comme chaînes
  write_options:
    index: false        # ne pas écrire l’index Pandas dans le CSV

# ------------------------------------------------------------------
# Choix du moteur du pipeline
# ------------------------------------------------------------------
pipeline:
  # 2 pipelines possibles : "tesseract_llm", "vlm_llm" ou "vlm_vlm"
  extraction_engine: "tesseract_llm"
  # Nombre de lignes traitées par batch pour l'extraction
  batch_size: 50
  # Nombre de lignes traitées par batch pour la recherche des PDFs (pretraitement)
  pretraitement_batch_size: 2